# # spatial_q_mamba/config.yaml


                  ####################   Grid is 10 #####################
paths:
  gloss_dict: "/shared/home/xvoice/Chingiz/slr_project_ms_corr_mamba/data/Phoenix-2014/gloss2ids.pkl"
  train_data: "/shared/home/xvoice/Chingiz/slr_project_ms_corr_mamba/data/tokenized_KP_gpu_10/phoenix-2014_10.train"
  dev_data:   "/shared/home/xvoice/Chingiz/slr_project_ms_corr_mamba/data/tokenized_KP_gpu_10/phoenix-2014_10.dev"
  test_data:  "/shared/home/xvoice/Chingiz/slr_project_ms_corr_mamba/data/tokenized_KP_gpu_10/phoenix-2014_10.test"
  # Where to save logs and models
  output_dir: "./experiments/px10-emb2"

model:
  num_joints: 133
  token_embed_dim: 2
  model_dim: 512     # 512   73.8% WER
  compress_factor: 4 # 4     73.8% WER
  num_layers: 4
  dropout: 0.4

training:
  batch_size: 2
  epochs: 100
  learning_rate: 0.0001
  save_every: 5
  print_every: 100







#                     ####################   Grid is 10,   Best WER: 67.98%  #####################
# paths:
#   gloss_dict: "/shared/home/xvoice/Chingiz/slr_project_ms_corr_mamba/data/Phoenix-2014/gloss2ids.pkl"
#   train_data: "/shared/home/xvoice/Chingiz/slr_project_ms_corr_mamba/data/tokenized_KP_gpu_10/phoenix-2014_10.train"
#   dev_data:   "/shared/home/xvoice/Chingiz/slr_project_ms_corr_mamba/data/tokenized_KP_gpu_10/phoenix-2014_10.dev"
#   test_data:  "/shared/home/xvoice/Chingiz/slr_project_ms_corr_mamba/data/tokenized_KP_gpu_10/phoenix-2014_10.test"
#   # Where to save logs and models
#   output_dir: "./experiments/run_v2"

# model:
#   num_joints: 133
#   token_embed_dim: 8
#   model_dim: 512
#   compress_factor: 4
#   num_layers: 4
#   dropout: 0.4

# training:
#   batch_size: 2
#   epochs: 100
#   learning_rate: 0.0001
#   save_every: 5
#   print_every: 50